In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tqdm import tqdm
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('data/test_mod21c3.csv')
df.head()

,year,date,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]",...,"[109.62590569752581, 2.016717812848326]","[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]"
0,2023,2023_01_01,307.18,307.18,305.01,307.18,307.18,307.18,307.18,305.01,...,302.85,302.85,302.85,302.85,302.85,302.85,307.236,307.236,307.236,305.493333
1,2023,2023_02_01,306.48,306.48,304.50,306.48,306.48,306.48,306.48,304.50,...,300.26,300.26,300.26,300.26,300.26,300.26,307.342,307.342,307.342,304.380000
2,2023,2023_03_01,306.02,306.02,305.68,306.02,306.02,306.02,306.02,305.68,...,306.00,306.00,306.00,306.00,306.00,306.00,307.448,307.448,307.448,303.200000
3,2023,2023_04_01,309.36,309.36,307.48,309.36,309.36,309.36,309.36,307.48,...,305.48,305.48,305.48,305.48,305.48,305.48,307.554,307.554,307.554,304.160000
4,2023,2023_05_01,307.72,307.72,306.76,307.72,307.72,307.72,307.72,306.76,...,307.26,307.26,307.26,307.26,307.26,307.26,307.660,307.660,307.660,307.720000

In [3]:
df = df.drop(columns=['year', 'date'])
df.head()

,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]","[110.64998512142206, -3.013847778220995]","[110.65896827426326, -3.013847778220995]",...,"[109.62590569752581, 2.016717812848326]","[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]"
0,307.18,307.18,305.01,307.18,307.18,307.18,307.18,305.01,305.01,307.18,...,302.85,302.85,302.85,302.85,302.85,302.85,307.236,307.236,307.236,305.493333
1,306.48,306.48,304.50,306.48,306.48,306.48,306.48,304.50,304.50,306.48,...,300.26,300.26,300.26,300.26,300.26,300.26,307.342,307.342,307.342,304.380000
2,306.02,306.02,305.68,306.02,306.02,306.02,306.02,305.68,305.68,306.02,...,306.00,306.00,306.00,306.00,306.00,306.00,307.448,307.448,307.448,303.200000
3,309.36,309.36,307.48,309.36,309.36,309.36,309.36,307.48,307.48,309.36,...,305.48,305.48,305.48,305.48,305.48,305.48,307.554,307.554,307.554,304.160000
4,307.72,307.72,306.76,307.72,307.72,307.72,307.72,306.76,306.76,307.72,...,307.26,307.26,307.26,307.26,307.26,307.26,307.660,307.660,307.660,307.720000

In [4]:
def create_window(dataframe, window_size, slide_size):
    input_window_list = []
    label_window_list = []
    # Iterate over the columns
    for col in tqdm(dataframe.columns):
        # Iterate over the rows in the current column with a sliding window
        for i in range(0, len(dataframe[col]) - window_size + 1, slide_size):
            input_window = dataframe[col].iloc[i:i + window_size]
            input_window_list.append(input_window)

            label_window = dataframe[col].iloc[i:i + slide_size]
            label_window_list.append(label_window)
    return input_window_list, label_window_list

In [5]:
window_size = 3
slide_size = 1

test_input_list, test_label_list = create_window(df, window_size, slide_size)

100%|██████████| 147695/147695 [01:15<00:00, 1955.58it/s]

In [6]:
x_test = np.array(test_input_list)
y_test = np.array(test_label_list)

In [7]:
x_test = x_test.reshape(x_test.shape[0], x_test.shape[1], 1)

In [8]:
model = tf.keras.models.load_model('models/model_2_3.keras')

In [9]:
y_pred = model.predict(x_test)

46155/46155 [==============================] - 109s 2ms/step

In [10]:
print(y_test.shape)
print(y_pred.shape)

(1476950, 1)
(1476950, 1)

In [11]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
print('Root Mean Square Error:', rmse)

Root Mean Square Error: 2.5751540621909057