In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/kaggle/input/west-kalimantan-mod21c3/data/data_mod21c3.csv')

In [3]:
df.head(15)

,year,date,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]",...,"[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]","[109.0958996798953, 2.079599882736692]"
0,2019,2019_01_01,307.06,307.06,304.88,307.06,307.06,307.06,307.06,304.88,...,303.44,303.44,303.44,303.44,303.44,NaN,NaN,NaN,302.48,NaN
1,2019,2019_02_01,308.28,308.28,306.64,308.28,308.28,308.28,308.28,306.64,...,297.28,297.28,297.28,297.28,297.28,NaN,NaN,NaN,302.96,NaN
2,2019,2019_03_01,307.98,307.98,306.94,307.98,307.98,307.98,307.98,306.94,...,306.88,306.88,306.88,306.88,306.88,303.98,303.98,303.98,305.38,NaN
3,2019,2019_04_01,308.26,308.26,306.78,308.26,308.26,308.26,308.26,306.78,...,304.98,304.98,304.98,304.98,304.98,303.60,303.60,303.60,307.60,NaN
4,2019,2019_05_01,308.22,308.22,306.42,308.22,308.22,308.22,308.22,306.42,...,308.76,308.76,308.76,308.76,308.76,NaN,NaN,NaN,NaN,NaN
5,2019,2019_06_01,305.88,305.88,304.96,305.88,305.88,305.88,305.88,304.96,...,307.44,307.44,307.44,307.44,307.44,NaN,NaN,NaN,302.40,NaN
6,2019,2019_07_01,305.46,305.46,304.80,305.46,305.46,305.46,305.46,304.80,...,307.40,307.40,307.40,307.40,307.40,NaN,NaN,NaN,304.68,NaN
7,2019,2019_08_01,305.92,305.92,304.70,305.92,305.92,305.92,305.92,304.70,...,306.70,306.70,306.70,306.70,306.70,NaN,NaN,NaN,303.32,NaN
8,2019,2019_09_01,307.54,307.54,303.78,307.54,307.54,307.54,307.54,303.78,...,307.34,307.34,307.34,307.34,307.34,305.14,305.14,305.14,306.88,NaN
9,2019,2019_10_01,307.72,307.72,307.48,307.72,307.72,307.72,307.72,307.48,...,306.66,306.66,306.66,306.66,306.66,314.26,314.26,314.26,306.98,NaN
10,2019,2019_11_01,309.50,309.50,307.92,309.50,309.50,309.50,309.50,307.92,...,303.32,303.32,303.32,303.32,303.32,NaN,NaN,NaN,300.32,NaN
11,2019,2019_12_01,308.98,308.98,307.12,308.98,308.98,308.98,308.98,307.12,...,303.84,303.84,303.84,303.84,303.84,NaN,NaN,NaN,NaN,NaN
12,2020,2020_01_01,308.40,308.40,305.86,308.40,308.40,308.40,308.40,305.86,...,302.50,302.50,302.50,302.50,302.50,NaN,NaN,NaN,NaN,NaN
13,2020,2020_02_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.96,NaN
14,2020,2020_03_01,309.38,309.38,309.16,309.38,309.38,309.38,309.38,309.16,...,303.68,303.68,303.68,303.68,303.68,NaN,NaN,NaN,306.32,NaN

In [4]:
df.describe()

,year,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]","[110.64998512142206, -3.013847778220995]",...,"[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]","[109.0958996798953, 2.079599882736692]"
count,60.000000,58.000000,58.000000,47.000000,58.000000,58.000000,58.000000,58.000000,47.000000,47.000000,...,56.000000,56.000000,56.000000,56.000000,56.000000,22.000000,22.000000,22.000000,49.000000,0.0
mean,2021.000000,307.693448,307.693448,306.278298,307.693448,307.693448,307.693448,307.693448,306.278298,306.278298,...,306.012143,306.012143,306.012143,306.012143,306.012143,306.274545,306.274545,306.274545,305.551429,NaN
std,1.426148,1.251107,1.251107,1.513406,1.251107,1.251107,1.251107,1.251107,1.513406,1.513406,...,3.030405,3.030405,3.030405,3.030405,3.030405,2.364622,2.364622,2.364622,1.811105,NaN
min,2019.000000,304.960000,304.960000,303.640000,304.960000,304.960000,304.960000,304.960000,303.640000,303.640000,...,297.280000,297.280000,297.280000,297.280000,297.280000,303.600000,303.600000,303.600000,300.320000,NaN
25%,2020.000000,306.670000,306.670000,305.090000,306.670000,306.670000,306.670000,306.670000,305.090000,305.090000,...,304.810000,304.810000,304.810000,304.810000,304.810000,304.545000,304.545000,304.545000,304.380000,NaN
50%,2021.000000,307.720000,307.720000,306.420000,307.720000,307.720000,307.720000,307.720000,306.420000,306.420000,...,305.950000,305.950000,305.950000,305.950000,305.950000,305.880000,305.880000,305.880000,305.840000,NaN
75%,2022.000000,308.445000,308.445000,307.340000,308.445000,308.445000,308.445000,308.445000,307.340000,307.340000,...,307.340000,307.340000,307.340000,307.340000,307.340000,307.610000,307.610000,307.610000,306.920000,NaN
max,2023.000000,309.880000,309.880000,309.900000,309.880000,309.880000,309.880000,309.880000,309.900000,309.900000,...,321.480000,321.480000,321.480000,321.480000,321.480000,314.260000,314.260000,314.260000,309.180000,NaN

In [5]:
# Count null values
df.isna().sum().sum()

153493

### Drop columns with all null values

In [6]:
# Count columns with all null values
df.isna().all().sum()

87

In [7]:
# Drop columns with all null values
df = df.dropna(axis=1, how='all')

# Check if columns with all null values are dropped
df.head(15)

,year,date,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]",...,"[109.62590569752581, 2.016717812848326]","[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]"
0,2019,2019_01_01,307.06,307.06,304.88,307.06,307.06,307.06,307.06,304.88,...,303.44,303.44,303.44,303.44,303.44,303.44,NaN,NaN,NaN,302.48
1,2019,2019_02_01,308.28,308.28,306.64,308.28,308.28,308.28,308.28,306.64,...,297.28,297.28,297.28,297.28,297.28,297.28,NaN,NaN,NaN,302.96
2,2019,2019_03_01,307.98,307.98,306.94,307.98,307.98,307.98,307.98,306.94,...,306.88,306.88,306.88,306.88,306.88,306.88,303.98,303.98,303.98,305.38
3,2019,2019_04_01,308.26,308.26,306.78,308.26,308.26,308.26,308.26,306.78,...,304.98,304.98,304.98,304.98,304.98,304.98,303.60,303.60,303.60,307.60
4,2019,2019_05_01,308.22,308.22,306.42,308.22,308.22,308.22,308.22,306.42,...,308.76,308.76,308.76,308.76,308.76,308.76,NaN,NaN,NaN,NaN
5,2019,2019_06_01,305.88,305.88,304.96,305.88,305.88,305.88,305.88,304.96,...,307.44,307.44,307.44,307.44,307.44,307.44,NaN,NaN,NaN,302.40
6,2019,2019_07_01,305.46,305.46,304.80,305.46,305.46,305.46,305.46,304.80,...,307.40,307.40,307.40,307.40,307.40,307.40,NaN,NaN,NaN,304.68
7,2019,2019_08_01,305.92,305.92,304.70,305.92,305.92,305.92,305.92,304.70,...,306.70,306.70,306.70,306.70,306.70,306.70,NaN,NaN,NaN,303.32
8,2019,2019_09_01,307.54,307.54,303.78,307.54,307.54,307.54,307.54,303.78,...,307.34,307.34,307.34,307.34,307.34,307.34,305.14,305.14,305.14,306.88
9,2019,2019_10_01,307.72,307.72,307.48,307.72,307.72,307.72,307.72,307.48,...,306.66,306.66,306.66,306.66,306.66,306.66,314.26,314.26,314.26,306.98
10,2019,2019_11_01,309.50,309.50,307.92,309.50,309.50,309.50,309.50,307.92,...,303.32,303.32,303.32,303.32,303.32,303.32,NaN,NaN,NaN,300.32
11,2019,2019_12_01,308.98,308.98,307.12,308.98,308.98,308.98,308.98,307.12,...,303.84,303.84,303.84,303.84,303.84,303.84,NaN,NaN,NaN,NaN
12,2020,2020_01_01,308.40,308.40,305.86,308.40,308.40,308.40,308.40,305.86,...,302.50,302.50,302.50,302.50,302.50,302.50,NaN,NaN,NaN,NaN
13,2020,2020_02_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,303.96
14,2020,2020_03_01,309.38,309.38,309.16,309.38,309.38,309.38,309.38,309.16,...,303.68,303.68,303.68,303.68,303.68,303.68,NaN,NaN,NaN,306.32

### Fill null values "in between" with linear interpolation

In [8]:
# Fill null values "in between" with linear interpolation
df = df.interpolate(method='linear')

/tmp/ipykernel_17/1222509614.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df = df.interpolate(method='linear')

In [9]:
df.isna().sum().sum()

2463

In [10]:
# Remove columns when there are still null values
# df = df.dropna(axis=1, how='any')

### Fill null values on the first few row with the next value

In [11]:
# Fill null value on the first few row with the next value
df = df.bfill()

### Make sure no null values

In [12]:
df.describe()

,year,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]","[110.64998512142206, -3.013847778220995]",...,"[109.62590569752581, 2.016717812848326]","[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]"
count,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,...,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000,60.000000
mean,2021.000000,307.743667,307.743667,306.271500,307.743667,307.743667,307.743667,307.743667,306.271500,306.271500,...,305.872667,305.872667,305.872667,305.872667,305.872667,305.872667,306.507667,306.507667,306.507667,305.539000
std,1.426148,1.260889,1.260889,1.432955,1.260889,1.260889,1.260889,1.260889,1.432955,1.432955,...,2.983232,2.983232,2.983232,2.983232,2.983232,2.983232,2.202053,2.202053,2.202053,1.807167
min,2019.000000,304.960000,304.960000,303.640000,304.960000,304.960000,304.960000,304.960000,303.640000,303.640000,...,297.280000,297.280000,297.280000,297.280000,297.280000,297.280000,303.600000,303.600000,303.600000,300.320000
25%,2020.000000,306.730000,306.730000,305.167500,306.730000,306.730000,306.730000,306.730000,305.167500,305.167500,...,304.740000,304.740000,304.740000,304.740000,304.740000,304.740000,304.779500,304.779500,304.779500,304.395000
50%,2021.000000,307.810000,307.810000,306.330000,307.810000,307.810000,307.810000,307.810000,306.330000,306.330000,...,305.780000,305.780000,305.780000,305.780000,305.780000,305.780000,306.485333,306.485333,306.485333,305.810000
75%,2022.000000,308.550000,308.550000,307.480000,308.550000,308.550000,308.550000,308.550000,307.480000,307.480000,...,307.295000,307.295000,307.295000,307.295000,307.295000,307.295000,307.451000,307.451000,307.451000,306.935000
max,2023.000000,309.880000,309.880000,309.900000,309.880000,309.880000,309.880000,309.880000,309.900000,309.900000,...,321.480000,321.480000,321.480000,321.480000,321.480000,321.480000,314.260000,314.260000,314.260000,309.180000

In [13]:
df.isna().sum().sum()

0

In [14]:
df.head(15)

,year,date,"[110.65896827426326, -3.0318140839033854]","[110.66795142710446, -3.0318140839033854]","[110.64998512142206, -3.02283093106219]","[110.65896827426326, -3.02283093106219]","[110.66795142710446, -3.02283093106219]","[110.67693457994565, -3.02283093106219]","[110.68591773278685, -3.02283093106219]","[110.64100196858087, -3.013847778220995]",...,"[109.62590569752581, 2.016717812848326]","[109.61692254468461, 2.025700965689521]","[109.62590569752581, 2.025700965689521]","[109.61692254468461, 2.0346841185307163]","[109.62590569752581, 2.0346841185307163]","[109.62590569752581, 2.0436672713719113]","[109.62590569752581, 2.0526504242131067]","[109.634888850367, 2.0526504242131067]","[109.634888850367, 2.0616335770543017]","[109.1048828327365, 2.070616729895497]"
0,2019,2019_01_01,307.06,307.06,304.88,307.06,307.06,307.06,307.06,304.88,...,303.44,303.44,303.44,303.44,303.44,303.44,303.980000,303.980000,303.980000,302.480000
1,2019,2019_02_01,308.28,308.28,306.64,308.28,308.28,308.28,308.28,306.64,...,297.28,297.28,297.28,297.28,297.28,297.28,303.980000,303.980000,303.980000,302.960000
2,2019,2019_03_01,307.98,307.98,306.94,307.98,307.98,307.98,307.98,306.94,...,306.88,306.88,306.88,306.88,306.88,306.88,303.980000,303.980000,303.980000,305.380000
3,2019,2019_04_01,308.26,308.26,306.78,308.26,308.26,308.26,308.26,306.78,...,304.98,304.98,304.98,304.98,304.98,304.98,303.600000,303.600000,303.600000,307.600000
4,2019,2019_05_01,308.22,308.22,306.42,308.22,308.22,308.22,308.22,306.42,...,308.76,308.76,308.76,308.76,308.76,308.76,303.908000,303.908000,303.908000,305.000000
5,2019,2019_06_01,305.88,305.88,304.96,305.88,305.88,305.88,305.88,304.96,...,307.44,307.44,307.44,307.44,307.44,307.44,304.216000,304.216000,304.216000,302.400000
6,2019,2019_07_01,305.46,305.46,304.80,305.46,305.46,305.46,305.46,304.80,...,307.40,307.40,307.40,307.40,307.40,307.40,304.524000,304.524000,304.524000,304.680000
7,2019,2019_08_01,305.92,305.92,304.70,305.92,305.92,305.92,305.92,304.70,...,306.70,306.70,306.70,306.70,306.70,306.70,304.832000,304.832000,304.832000,303.320000
8,2019,2019_09_01,307.54,307.54,303.78,307.54,307.54,307.54,307.54,303.78,...,307.34,307.34,307.34,307.34,307.34,307.34,305.140000,305.140000,305.140000,306.880000
9,2019,2019_10_01,307.72,307.72,307.48,307.72,307.72,307.72,307.72,307.48,...,306.66,306.66,306.66,306.66,306.66,306.66,314.260000,314.260000,314.260000,306.980000
10,2019,2019_11_01,309.50,309.50,307.92,309.50,309.50,309.50,309.50,307.92,...,303.32,303.32,303.32,303.32,303.32,303.32,313.126667,313.126667,313.126667,300.320000
11,2019,2019_12_01,308.98,308.98,307.12,308.98,308.98,308.98,308.98,307.12,...,303.84,303.84,303.84,303.84,303.84,303.84,311.993333,311.993333,311.993333,301.533333
12,2020,2020_01_01,308.40,308.40,305.86,308.40,308.40,308.40,308.40,305.86,...,302.50,302.50,302.50,302.50,302.50,302.50,310.860000,310.860000,310.860000,302.746667
13,2020,2020_02_01,308.89,308.89,307.51,308.89,308.89,308.89,308.89,307.51,...,303.09,303.09,303.09,303.09,303.09,303.09,309.726667,309.726667,309.726667,303.960000
14,2020,2020_03_01,309.38,309.38,309.16,309.38,309.38,309.38,309.38,309.16,...,303.68,303.68,303.68,303.68,303.68,303.68,308.593333,308.593333,308.593333,306.320000

In [15]:
print('Minimum Values:', df.drop(['year', 'date'], axis=1).min().min())
print('Maximum Values:', df.drop(['year', 'date'], axis=1).max().max())
print('Total Count:', df.drop(['year', 'date'], axis=1).shape[0] * df.drop(['year', 'date'], axis=1).shape[1])

Minimum Values: 283.82
Maximum Values: 356.38
Total Count: 8861700

### Split data into training-validation, test, <s>and prediction</s>
1. Training-validation: 2019-2022
2. Test: 2023
3. <strike>prediction: 2024 or last 3 months</strike> (data taken separated on new file)

In [16]:
group_by_year = df.groupby('year')
df_training_validation = pd.concat([group_by_year.get_group(year) for year in range (2019, 2023)])
df_test = group_by_year.get_group(2023)

In [17]:
df_training_validation.to_csv('/kaggle/working/training_validation_mod21c3.csv', index=False)
df_test.to_csv('/kaggle/working/test_mod21c3.csv', index=False)
# df_predict.to_csv('data/predict_mod21c3.csv', index=False)